config/routes.rb
Rails.application.routes.draw do

  resources :texts
  get 'home/index'

  devise_for :users
  root :to => 'studies#index'
  get 'limited' => 'studies#show'
  get 'limited/view' => 'studies#view'
  get 'access' => 'studies#access'
  get 'flow' => 'studies#flow'
  get 'about' => 'studies#about'

end

app/models/text.rb
class Text < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

 def after_sign_in_path_for(resource)
    '/limited'
  end

  def after_sign_out_path_for(resource)
    '/'
  end

  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController

def index
end

def show
end

def access
end

def flow
end

def about
end

end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: [:show, :edit, :update, :destroy]

  # GET /texts
  # GET /texts.json
  def index
    @texts = Text.all
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
  end

  # GET /texts/new
  def new
    @text = Text.new
  end

  # GET /texts/1/edit
  def edit
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(text_params)

    respond_to do |format|
      if @text.save
        format.html { redirect_to @text, notice: 'Text was successfully created.' }
        format.json { render :show, status: :created, location: @text }
      else
        format.html { render :new }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texts/1
  # PATCH/PUT /texts/1.json
  def update
    respond_to do |format|
      if @text.update(text_params)
        format.html { redirect_to @text, notice: 'Text was successfully updated.' }
        format.json { render :show, status: :ok, location: @text }
      else
        format.html { render :edit }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    @text.destroy
    respond_to do |format|
      format.html { redirect_to texts_url, notice: 'Text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_params
      params.require(:text).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>公文 松戸東口教室</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="top-space">
  </div>
  <div class="bar">

    <% if user_signed_in? %>
      <ul class="right-bar">
      <li class="menu">
<%= link_to "トップページ", destroy_user_session_path, method: :delete %>
      </li>
      <li class="menu">
        <a  href="/access">アクセス</a>
      </li>
      <li class="menu">
        <a  href="/flow">入会までの流れ</a>
      </li>
      <li class="menu">
        <a  href="/about">教室について</a>
      </li>
      </ul>
    <% else %>
      <ul class="right-bar">
          <!-- <li class="menu">
            <a  href="/users/sign_up">新規登録</a>
          </li> -->
      <li class="menu">
        <a  href="/users/sign_in">会員ページ</a>
      </li>
      <li class="menu">
        <a  href="/access">アクセス</a>
      </li>
      <li class="menu">
        <a  href="/flow">入会までの流れ</a>
      </li>
      <li class="menu">
        <a  href="/about">教室について</a>
      </li>
      <li class="back">
        <a  href="/">
          <img src="/assets/rogo.png" class="rogo">
        </a>
      </li>

         <!--  <li class="menu">
            <a  href="whk_obog/register">問い合わせ</a>
          </li> -->
        </ul>
    <% end %>

  </div>
  <div class="small-space">
  </div>
</header>

<%= yield %>

  <div class="footer">
    <font size="3" color="white"><center>Copyright(c) 公文　松戸駅東口教室 All Rights Reserved.</font></center>
  </div>

</body>
</html>

app/views/studies/about.html.erb
  <div class="good-space"></div>

  <div class="contents">
     <!--  <div class="shikaku"></div> -->
      <font size="5">安全な学習環境</font>
      <div class="under-bar"></div>
      <div class="small-space"></div>

  <div class="about">
    <img src="/assets/about1.png" class="about1">
  </div>

  <div class="good-space"></div>



  <!--  <div class="shikaku"></div> -->
  <font size="5">充実した学習サポート</font>
  <div class="under-bar"></div>
  <div class="top-space"></div>

  <div class="about">
    <img src="/assets/about2.png" class="about2">
  </div>

  <div class="about">
    <img src="/assets/about3.png" class="about3">
  </div>

  <div class="about">
    <img src="/assets/about4.png" class="about2">
  </div>

    <div class="good-space">
    </div>
  </div>

app/views/studies/access.html.erb
<div  class="map">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3236.6970925681885!2d139.8987305154226!3d35.782816380170765!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x601884fb89b13725%3A0x6fb565739e36fb8f!2z44CSMjcxLTAwOTIg5Y2D6JGJ55yM5p2-5oi45biC5p2-5oi477yR77yS77yZ77yS4oiS77yRIOOCt-ODhuOCo-ODj-OCpOODhOadvuaIuA!5e0!3m2!1sja!2sjp!4v1483675247194" width="100%" height="300px" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

<div class="contents">

  <div class="right-contents">
    <div class="good-space">
    </div>
    <img src="/assets/place.png" class="place-image">
    <b><center>松戸駅東口教室　外観</center></b>
    <div class="good-space">
    </div>
  </div>


  <div class="kamoku">
     <div class="good-space">
    </div>
  <!--   <div class="shikaku"></div> -->
    <font size="5">所在地</font>
    <div class="under-bar"></div>
    <div class="small-space"></div>
    〒271-0092<br>
    千葉県松戸市松戸１２９２－１<br>
    シティハイツ松戸２０６号

    <div class="good-space">
    </div>
  <!--   <div class="shikaku"></div> -->
    <font size="5">交通</font>
    <div class="under-bar"></div>
    <div class="small-space"></div>
    「松戸駅」徒歩3分（常磐線,新京成線）<br><br>
    ※道に迷われた際は、遠慮なくご連絡ください。
  </div>

</div>

app/views/studies/flow.html.erb
  <div class="good-space"></div>

  <div class="contents">
    <!--   <div class="shikaku"></div> -->
      <font size="5">入会までの流れ</font>
      <div class="under-bar"></div>
      <div class="top-space"></div>

  <div class="flows">
    <img src="/assets/flow1.jpg" class="flow-photo">
  </div>
  <div class="flows">
    <img src="/assets/flow2.jpg" class="flow-photo">
  </div>
  <div class="flows">
    <img src="/assets/flow3.jpg" class="flow-photo">
  </div>


  電話：047-703-7083<br>
  メール：kumon-matsudost-east@ozzio.jp<br>
  WEBサイト：
  <a href="https://www.kumon.ne.jp/enter/search/classroom/1557320092/index.html?lid=hist_000">こちら</a><br>

  <div class="good-space"></div>



<!--   <div class="shikaku"></div> -->
  <font size="5">会費について</font>
  <div class="under-bar"></div>
  <div class="top-space"></div>
  <div class="flows">
    <img src="/assets/flow4.jpg" class="flow-photo">
  </div>
  <div class="flows">
    <img src="/assets/flow5.jpg" class="flow-photo">
  </div>





    <div class="good-space">
    </div>
  </div>

app/views/studies/index.html.erb
  <div class="photo">
    <img src="/assets/studing_children.jpg" alt="集合写真" class="top-image">
  </div>

<div class="good-space">
</div>

  <div class="contents">

    <div class="right-contents">
      <img src="/assets/bosyuu.png" alt="入会募集" class="bosyuu-image">
      <div class="adress">
        <b><font size="4">お問合せ電話番号</font><br></b>
        <img src="/assets/tel.png" class="tel">
      教室 047-703-7083<br>
      携帯 080-1187-3626
      </div>
      <!-- <div class="adress">
        <b><font size="4">住所</font><br></b>
        〒271-0092<br>
        千葉県松戸市松戸１２９２－１<br>
        シティハイツ松戸２０６号
      </div> -->
      <a href="http://www.kumon.ne.jp/"><div class="link-kumon">KUMON　リンク</div></a>
      <a href="https://www.kumon.ne.jp/enter/search/classroom/1557320092/index.html"><div class="link-matudo">KUMON教室ページ　リンク</div></a>
    </div>

    <div class="thin-space">
    </div>

    <div class="kamoku">
     <!-- <div class="shikaku"></div> -->
      <font size="5">学べる学科・日時</font>
      <div class="under-bar"></div>

      <div class="small-space"></div>
      ■対象：2歳から社会人まで
      <div class="small-space"></div>
      ■学べる学科：数・英・国
      <div class="small-space"></div>
      ■学べる日時：月・火・木・金 （うち2回）<br>
      　　　　　　　14:00〜20:00の間いつでも入室可<br>
      　　　　　　　同月内振替制度有り<br>
      　　　　　　（詳しくは教室へお問い合わせ下さい）<br>

      <div class="good-space">
      </div>
      <!--  <div class="shikaku"></div> -->
      <font size="5">指導者からのメッセージ</font>
      <div class="under-bar"></div>
      <div class="small-space"></div>
      こんにちは。<br>
      KUMON松戸駅東口教室の根岸優樹（ねぎしゆうき）です。<br>
      公文式は個人別のちょうどの学習で子どもの能力の可能性を追求できます。<br>
      子どもたちが伸びることは嬉しく、もっと伸ばせるのではないかという好奇心と日々の感動が私の仕事への原動力となります。<br>
      ひとり一人を公文式学習を通して楽しみながらも甘やかさずに大切に育て、思考力を身に付けて自学自習していけるお子さまに育っていって欲しいと思っています。<br>
      学年を超えた学習に進むにつれて他の面での発達にも驚くことが多く能力開発の大切さを実感しています。<br>
      新しい課題に自学自習で取り組んでいる素晴らしいお子さま方の学習の様子を是非見に来てください。<br>
      見学の際は事前にご連絡の上お越しください。<br>
      お待ちしております。
      <div class="good-space">
      </div>

    </div>
  </div>

app/views/studies/show.html.erb
  <div class="photo">
    <img src="/assets/art-limited.jpg" alt="会員限定ページ" class="top-image">
  </div>

<div class="good-space">
</div>

  <div class="contents">
    <!--   <div class="shikaku"></div> -->
      <font size="5">会員の皆さまへ</font>
      <div class="under-bar"></div>
      <div class="small-space"></div>
     いつも公文式へのご理解と温かいご協力に、心から感謝致しております。<br>
      この会員ページでは「日頃の教室風景」や「会員さま向けのメッセージ」などを紹介していきたいと思っております。

      <div class="good-space">
      </div>
    <!--   <div class="shikaku"></div> -->
      <font size="5">コンテンツ</font>
      <div class="under-bar"></div>
      <div class="small-space"></div>
      以下をクリックすると、イベントの様子を、写真でご覧いただけます。<br>
      写真は、ご自由にダウンロードしてください。

    <ul class="limited_event">
      <a href="/limited/view">
      <li class="event">
      2016年12月22日<br>
      松戸駅東口教室クリスマス会
        <div class="event_photo">
        <img src="/assets/santa.jpg" alt="クリスマス会" class="santa">
        </div>
      </li>
      </a>
    </ul>
    <div class="good-space">
    </div>
  </div>

app/views/studies/view.html.erb
  <div class="contents">
    <div class="good-space">
    </div>
    <!--   <div class="shikaku"></div> -->
      <font size="5">実施概要</font>
      <div class="under-bar"></div>
      <div class="small-space"></div>
      2016年12月22日<br>
      恒例の松戸駅東口教室クリスマス会を開催しました。<br>
      <div class="small-space"></div>
      幼児の部では、<br>
      2グループに分かれて学習の様子を参観する
      教材解法タイムを設けました。<br>
      みんないつもよりかっこよく立派に見えました^_^<br>
      ビンゴゲームでは数字を見つけるのが大変だったけど楽しかったですね！<br>
      <div class="small-space"></div>
      小学生の部では、<br>
      当教室のスタッフによる紙芝居と東京大学奇術愛好会の柳本さんによるマジックショーがありました。<br>
      次々に繰り広げられるマジックに大歓声があがっていました。

      <div class="good-space">
      </div>
    <!--   <div class="shikaku"></div> -->
      <font size="5">フォトアルバム</font>
      <div class="under-bar"></div>
      <div class="small-space"></div>
      <img src="/assets/01_01.JPG"  class="views">
      <img src="/assets/01_02.JPG"  class="views">
      <img src="/assets/01_03.JPG"  class="views">
      <img src="/assets/01_04.JPG"  class="views">
      <img src="/assets/01_05.JPG"  class="views">
      <img src="/assets/01_06.JPG"  class="views">
      <img src="/assets/01_07.JPG"  class="views">
      <img src="/assets/01_08.JPG"  class="views">
      <img src="/assets/01_09.JPG"  class="views">
      <img src="/assets/01_10.JPG"  class="views">
      <img src="/assets/01_11.JPG"  class="views">
      <img src="/assets/01_12.JPG"  class="views">
      <img src="/assets/01_13.JPG"  class="views">
      <img src="/assets/01_14.JPG"  class="views">
      <img src="/assets/01_15.JPG"  class="views">
      <img src="/assets/01_16.JPG"  class="views">
      <img src="/assets/01_17.JPG"  class="views">
      <img src="/assets/01_18.JPG"  class="views">
      <img src="/assets/01_19.JPG"  class="views">
      <img src="/assets/01_20.JPG"  class="views">
      <img src="/assets/01_21.JPG"  class="views">
      <img src="/assets/01_22.JPG"  class="views">
      <img src="/assets/01_23.JPG"  class="views">
      <img src="/assets/01_24.JPG"  class="views">
      <img src="/assets/01_25.JPG"  class="views">
      <img src="/assets/01_26.JPG"  class="views">
      <img src="/assets/01_27.JPG"  class="views">
      <img src="/assets/01_28.JPG"  class="views">
      <img src="/assets/01_29.JPG"  class="views">
      <img src="/assets/01_30.JPG"  class="views">
      <img src="/assets/01_31.JPG"  class="views">
      <img src="/assets/01_32.JPG"  class="views">
      <img src="/assets/01_33.JPG"  class="views">
      <img src="/assets/01_34.JPG"  class="views">
      <img src="/assets/01_35.JPG"  class="views">
      <img src="/assets/01_36.JPG"  class="views">
      <img src="/assets/01_37.JPG"  class="views">
      <img src="/assets/01_38.JPG"  class="views">
      <img src="/assets/01_39.JPG"  class="views">
      <img src="/assets/01_40.JPG"  class="views">
      <img src="/assets/01_41.JPG"  class="views">
      <img src="/assets/01_42.JPG"  class="views">
      <img src="/assets/01_43.JPG"  class="views">
      <img src="/assets/01_44.JPG"  class="views">
      <img src="/assets/01_45.JPG"  class="views">
      <img src="/assets/01_46.JPG"  class="views">
      <img src="/assets/01_47.JPG"  class="views">
      <img src="/assets/01_48.JPG"  class="views">
      <img src="/assets/01_49.JPG"  class="views">
      <img src="/assets/01_50.JPG"  class="views">
      <img src="/assets/01_51.JPG"  class="views">
      <img src="/assets/01_52.JPG"  class="views">
      <img src="/assets/01_53.JPG"  class="views">
      <img src="/assets/01_54.JPG"  class="views">
      <img src="/assets/01_55.JPG"  class="views">
      <img src="/assets/01_56.JPG"  class="views">
      <img src="/assets/01_57.JPG"  class="views">
      <img src="/assets/01_58.JPG"  class="views">
      <img src="/assets/01_59.JPG"  class="views">
      <img src="/assets/01_60.JPG"  class="views">
      <img src="/assets/01_61.JPG"  class="views">

  </div>

app/views/texts/_form.html.erb
<%= form_for(@text) do |f| %>
  <% if @text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text.errors.count, "error") %> prohibited this text from being saved:</h2>

      <ul>
      <% @text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/texts/edit.html.erb
<h1>Editing Text</h1>

<%= render 'form' %>

<%= link_to 'Show', @text %> |
<%= link_to 'Back', texts_path %>

app/views/texts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Texts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @texts.each do |text| %>
      <tr>
        <td><%= text.title %></td>
        <td><%= text.body %></td>
        <td><%= link_to 'Show', text %></td>
        <td><%= link_to 'Edit', edit_text_path(text) %></td>
        <td><%= link_to 'Destroy', text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text', new_text_path %>

app/views/texts/new.html.erb
<h1>New Text</h1>

<%= render 'form' %>

<%= link_to 'Back', texts_path %>

app/views/texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @text.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @text.body %>
</p>

<%= link_to 'Edit', edit_text_path(@text) %> |
<%= link_to 'Back', texts_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>